### ISSUE TITLE
How to find the source code of the v2.0.4?

### ISSUE THREAD

**Issue by Abdelkrim** [peopleware/net-ppwcode-vernacular-nhibernate#11]
to whom it may concern, we are using Vernacular for many years but they are new bugs in our code that require the access to the source code. 

1/ I would like to find how to download the source code based on the following packages.config.
Looking at the tags didn't lead me anywhere (or did I looked in the wrong direction?)

Could you help me? 
thank you in advance

```
<package id="PPWCode.Util.OddsAndEnds.II" version="1.3.0" targetFramework="net461" />
<package id="PPWCode.Vernacular.Exceptions.II" version="1.0.0" targetFramework="net461" />
<package id="PPWCode.Vernacular.NHibernate.I" version="2.0.4" targetFramework="net461" />
<package id="PPWCode.Vernacular.NHibernate.I.Test" version="2.0.4" targetFramework="net461" />
<package id="PPWCode.Vernacular.Persistence.II" version="2.0.0" targetFramework="net461" />
<package id="PPWcode.Vernacular.Semantics.II" version="1.0.0" targetFramework="net461" />
```

**Comment by dvdwouwe** [comment]
Hi,


1. Checkout the repo:
git clone https://github.com/peopleware/net-ppwcode-vernacular-nhibernate.git

2. If you run following command, to get all the tags:
git tag -n

3. Checkout the tag I/2.0.4:
git checkout I/2.0.4

Or you can do this if you are a visual studio user, using team Explorer (VS2017)
![image](https://user-images.githubusercontent.com/1530070/50237420-28d10500-03bd-11e9-85f5-dd5c312515cc.png)

Then right click and checkout.

Then you should have your version 2.0.4.

PS
This branch is not active anymore for more then 2 years, you can better switch to II/next branch

- support for .Net standard
- using latest nHibernate
- powerfull mapping by code
- better handling of dialects, at the moment we support PostgresSQL, Firebird and SQL Server
- If you are using Castle Windsor as your Ioc container, then their is now a nHibernateFacility, which configure nHibernate in a breeze
- ...

**Comment by dvdwouwe** [comment]
Oeps, I closed it.
